### ISSUE TITLE
Missing spec aarch64-apple-darwin9 (Apple Silicon)

### ISSUE THREAD

**Issue by VitoVan** [lispgames/cl-sdl2-mixer#12]
The same as https://github.com/lispgames/cl-sdl2/issues/154

**Comment by VitoVan** [comment]
In the meantime, this fork might help:

https://github.com/ellisvelo/cl-sdl2-mixer

**Comment by VitoVan** [comment]
@iamFIREcracker

Hi Matteo Landi, are you interested in doing this one? I see you have done it for other cl-sdl2 related repos, good job by the way.

**Comment by iamFIREcracker** [comment]
@VitoVan - never used this library before but ran the "dance" on the repo anyways and got the following specs generated: https://github.com/iamFIREcracker/cl-sdl2-mixer/tree/aarch64-apple-darwin9  Mind giving it a go and confirm if it works?  I will then open up an PR with detailed instructions on how to reproduce this.

**Comment by VitoVan** [comment]
@iamFIREcracker Thank you!

I can confirm this fork is working well:

https://github.com/ellisvelo/cl-sdl2-mixer

I will check your fork in a minute, will let you know if it worked for me.

**Comment by VitoVan** [comment]
@iamFIREcracker Hi Matteo Landi! Good news! Your fork worked like a charm.

Together with these two:

https://github.com/iamFIREcracker/cl-sdl2/tree/aarch64-apple-darwin9
https://github.com/iamFIREcracker/cl-sdl2-mixer/tree/aarch64-apple-darwin9

I can play music with sdl2_mixer smoothly.

Thank you!

**Comment by fitzsim** [comment]
Fixed by #13.

**Comment by fitzsim** [comment]
Fixed by #13.
