### ISSUE TITLE
Add to Quicklisp

### ISSUE THREAD

**Issue by Zulu-Inuoe** [lispgames/cl-sdl2-mixer#3]
Title explains it all.

Would be great to have this in quicklisp as cl-sdl2-image and cl-sdl2-ttf are

**Comment by rpav** [comment]
This is more or less a community project; feel free to submit it.

**Comment by Zulu-Inuoe** [comment]
Done.

https://github.com/quicklisp/quicklisp-projects/issues/1300#event-1090679184
